name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 15.236.36.30 >> ~/.ssh/known_hosts

      - name: SSH Commands
        run: |
          ssh -o StrictHostKeyChecking=yes ubuntu@15.236.36.30 '
          cd spark-matcher
          git pull
          # Запуск нового контейнера
          docker run --restart=always -d --name spot-market-matcher-fuel-btc-new spot-market-matcher-fuel-btc
          # Проверка, успешно ли запущен новый контейнер
          if [ $(docker ps -q -f name=spot-market-matcher-fuel-btc-new) ]; then
          echo "New container started successfully. Removing old container."
          # Остановка и удаление старого контейнера
          docker stop spot-market-matcher-fuel-btc || true
          docker rm spot-market-matcher-fuel-btc || true
          else
          echo "Failed to start new container. Keeping the old one."
          fi 
          '
